name: Pull Request CI

on:
  pull_request:
    branches:
      - main
jobs:
  lint_and_test:
    name: Lint and Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: yarn
      - run: yarn lint
      - run: yarn test:ci
  database_setup:
    name: Setup Preview Database
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: yarn
      - name: Setup database
        env:
          DB_URL: postgresql://${{ secrets.COCKROACHDB_PREVIEW_USERNAME }}:${{ secrets.COCKROACHDB_PREVIEW_PASSWORD }}@${{ secrets.COCKROACHDB_PREVIEW_HOST }}:26257/${{ github.event.pull_request.head.sha }}?sslmode=verify-full
        run: yarn prisma migrate dev
  test_setup:
    name: Test Setup
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.waitForVercelPreviewDeployment.outputs.url }}
    steps:
      - name: Wait for Vercel preview deployment to be ready
        uses: patrickedqvist/wait-for-vercel-preview@main
        id: waitForVercelPreviewDeployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 300
  test_e2e:
    needs: [test_setup, database_setup]
    name: E2E Tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Prepare testing env
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: yarn
      - run: npx playwright install --with-deps
      - name: Run tests
        run: yarn test:e2e
        env:
          CI: false
          PLAYWRIGHT_TEST_BASE_URL: ${{ needs.test_setup.outputs.preview_url }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 30
